// This is generated by extract_h2olog_schema.pl. Do not edit it!
package main

/*
-- BigQuery DDL
create table `h2olog.quic` (
  `type` string,
  `dcid` string,
  `token_preview` string,
  `at` timestamp,
  `master_conn_id` int64,
  `stream_id` int64,
  `error_code` int64,
  `packet_num` int64,
  `packet_len` int64,
  `packet_type` int64,
  `frame_type` int64,
  `ack_only` int64,
  `largest_acked` int64,
  `bytes_acked` int64,
  `ack_delay` int64,
  `inflight` int64,
  `max_lost_pn` int64,
  `cwnd` int64,
  `first_octet` int64,
  `newly_acked` int64,
  `new_version` int64,
  `len` int64,
  `token_generation` int64,
  `limit` int64,
  `off` int64,
  `is_unidirectional` int64,
  `ret` int64,
  `h2o_conn_id` int64,
  `h2o_req_id` int64,
  `h2o_header_name` string,
  `h2o_header_value` string
);
*/

type quicEvent struct {
	Type             string `json:"type"`
	Dcid             string `json:"dcid"`
	TokenPreview     string `json:"token_preview"`
	At               int64  `json:"at"`
	MasterConnID     int64  `json:"master_conn_id"`
	StreamID         int64  `json:"stream_id"`
	ErrorCode        int64  `json:"error_code"`
	PacketNum        int64  `json:"packet_num"`
	PacketLen        int64  `json:"packet_len"`
	PacketType       int64  `json:"packet_type"`
	FrameType        int64  `json:"frame_type"`
	AckOnly          int64  `json:"ack_only"`
	LargestAcked     int64  `json:"largest_acked"`
	BytesAcked       int64  `json:"bytes_acked"`
	AckDelay         int64  `json:"ack_delay"`
	Inflight         int64  `json:"inflight"`
	MaxLostPn        int64  `json:"max_lost_pn"`
	Cwnd             int64  `json:"cwnd"`
	FirstOctet       int64  `json:"first_octet"`
	NewlyAcked       int64  `json:"newly_acked"`
	NewVersion       int64  `json:"new_version"`
	Len              int64  `json:"len"`
	TokenGeneration  int64  `json:"token_generation"`
	Limit            int64  `json:"limit"`
	Off              int64  `json:"off"`
	IsUnidirectional int64  `json:"is_unidirectional"`
	Ret              int64  `json:"ret"`
	H2oConnID        int64  `json:"h2o_conn_id"`
	H2oReqID         int64  `json:"h2o_req_id"`
	H2oHeaderName    string `json:"h2o_header_name"`
	H2oHeaderValue   string `json:"h2o_header_value"`
}
