// generated by extract_h2olog_schema.pl
package main

type quicEvent struct {
	Type             string `json:"type"`
	Dcid             string `json:"dcid"`
	TokenPreview     string `json:"token_preview"`
	At               int64  `json:"at"`
	MasterConnID     int64  `json:"master_conn_id"`
	StreamID         int64  `json:"stream_id"`
	ErrorCode        int64  `json:"error_code"`
	PacketNum        int64  `json:"packet_num"`
	PacketLen        int64  `json:"packet_len"`
	PacketType       int64  `json:"packet_type"`
	FrameType        int64  `json:"frame_type"`
	AckOnly          int64  `json:"ack_only"`
	LargestAcked     int64  `json:"largest_acked"`
	BytesAcked       int64  `json:"bytes_acked"`
	AckDelay         int64  `json:"ack_delay"`
	Inflight         int64  `json:"inflight"`
	MaxLostPn        int64  `json:"max_lost_pn"`
	Cwnd             int64  `json:"cwnd"`
	FirstOctet       int64  `json:"first_octet"`
	NewlyAcked       int64  `json:"newly_acked"`
	NewVersion       int64  `json:"new_version"`
	Len              int64  `json:"len"`
	TokenGeneration  int64  `json:"token_generation"`
	Limit            int64  `json:"limit"`
	Off              int64  `json:"off"`
	IsUnidirectional int64  `json:"is_unidirectional"`
	Ret              int64  `json:"ret"`
	H2oConnID        int64  `json:"h2o_conn_id"`
	H2oReqID         int64  `json:"h2o_req_id"`
	H2oHeaderName    string `json:"h2o_header_name"`
	H2oHeaderValue   string `json:"h2o_header_value"`
}
